export const CountryList = () => {
  return [
    {
      name: "Afghanistan",
      slug: "afghanistan",
      country_code: "+93",
    },
    {
      name: "Albania",
      slug: "albania",
      country_code: "+355",
    },
    {
      name: "Algeria",
      slug: "algeria",
      country_code: "+213",
    },
    {
      name: "Andorra",
      slug: "andorra",
      country_code: "+376",
    },
    {
      name: "Angola",
      slug: "angola",
      country_code: "+244",
    },
    {
      name: "Antigua and Barbuda",
      slug: "antigua_and_barbuda",
      country_code: "+1",
    },
    {
      name: "Argentina",
      slug: "argentina",
      country_code: "+54",
    },
    {
      name: "Armenia",
      slug: "armenia",
      country_code: "+374",
    },
    {
      name: "Australia",
      slug: "australia",
      country_code: "+61",
    },
    {
      name: "Austria",
      slug: "austria",
      country_code: "+43",
    },
    {
      name: "Azerbaijan",
      slug: "azerbaijan",
      country_code: "+994",
    },
    {
      name: "Bahamas",
      slug: "bahamas",
      country_code: "+1",
    },
    {
      name: "Bahrain",
      slug: "bahrain",
      country_code: "+973",
    },
    {
      name: "Bangladesh",
      slug: "bangladesh",
      country_code: "+880",
    },
    {
      name: "Barbados",
      slug: "barbados",
      country_code: "+1",
    },
    {
      name: "Belarus",
      slug: "belarus",
      country_code: "+375",
    },
    {
      name: "Belgium",
      slug: "belgium",
      country_code: "+32",
    },
    {
      name: "Belize",
      slug: "belize",
      country_code: "+501",
    },
    {
      name: "Benin",
      slug: "benin",
      country_code: "+229",
    },
    {
      name: "Bhutan",
      slug: "bhutan",
      country_code: "+975",
    },
    {
      name: "Bolivia",
      slug: "bolivia",
      country_code: "+591",
    },
    {
      name: "Bosnia and Herzegovina",
      slug: "bosnia_and_herzegovina",
      country_code: "+387",
    },
    {
      name: "Botswana",
      slug: "botswana",
      country_code: "+267",
    },
    {
      name: "Brazil",
      slug: "brazil",
      country_code: "+55",
    },
    {
      name: "Brunei",
      slug: "brunei",
      country_code: "+673",
    },
    {
      name: "Bulgaria",
      slug: "bulgaria",
      country_code: "+359",
    },
    {
      name: "Burkina Faso",
      slug: "burkina_faso",
      country_code: "+226",
    },
    {
      name: "Burundi",
      slug: "burundi",
      country_code: "+257",
    },
    {
      name: "Cambodia",
      slug: "cambodia",
      country_code: "+855",
    },
    {
      name: "Cameroon",
      slug: "cameroon",
      country_code: "+237",
    },
    {
      name: "Canada",
      slug: "canada",
      country_code: "+1",
    },
    {
      name: "Cape Verde",
      slug: "cape_verde",
      country_code: "+238",
    },
    {
      name: "Central African Republic",
      slug: "central_african_republic",
      country_code: "+236",
    },
    {
      name: "Chad",
      slug: "chad",
      country_code: "+235",
    },
    {
      name: "Chile",
      slug: "chile",
      country_code: "+56",
    },
    {
      name: "China",
      slug: "china",
      country_code: "+86",
    },
    {
      name: "Colombia",
      slug: "colombia",
      country_code: "+57",
    },
    {
      name: "Comoros",
      slug: "comoros",
      country_code: "+269",
    },
    {
      name: "Democratic Republic of  the Congo",
      slug: "democratic_republic_of_the_congo",
      country_code: "+242",
    },
    {
      name: "Republic of the Congo",
      slug: "republic_of_the_congo",
      country_code: "+243",
    },
    {
      name: "Costa Rica",
      slug: "costa_rica",
      country_code: "+506",
    },
    {
      name: "Côte D'Ivoire",
      slug: "côte_d_ivoire",
      country_code: "+225",
    },
    {
      name: "Croatia",
      slug: "croatia",
      country_code: "+385",
    },
    {
      name: "Cuba",
      slug: "cuba",
      country_code: "+53",
    },
    {
      name: "Cyprus",
      slug: "cyprus",
      country_code: "+357",
    },
    {
      name: "Czech Republic",
      slug: "czech_republic",
      country_code: "+420",
    },
    {
      name: "Denmark",
      slug: "denmark",
      country_code: "+45",
    },
    {
      name: "Djibouti",
      slug: "djibouti",
      country_code: "+253",
    },
    {
      name: "Dominica",
      slug: "dominica",
      country_code: "+1",
    },
    {
      name: "Dominican Republic",
      slug: "dominican_republic",
      country_code: "+1",
    },
    {
      name: "Ecuador",
      slug: "ecuador",
      country_code: "+593",
    },
    {
      name: "Egypt",
      slug: "egypt",
      country_code: "+20",
    },
    {
      name: "El Salvador",
      slug: "el_salvador",
      country_code: "+503",
    },
    {
      name: "Equatorial Guinea",
      slug: "equatorial_guinea",
      country_code: "+240",
    },
    {
      name: "Eritrea",
      slug: "eritrea",
      country_code: "+291",
    },
    {
      name: "Estonia",
      slug: "estonia",
      country_code: "+372",
    },
    {
      name: "Eswatini",
      slug: "eswatini",
      country_code: "+268",
    },
    {
      name: "Ethiopia",
      slug: "ethiopia",
      country_code: "+251",
    },
    {
      name: "Fiji",
      slug: "fiji",
      country_code: "+679",
    },
    {
      name: "Finland",
      slug: "finland",
      country_code: "+358",
    },
    {
      name: "France",
      slug: "france",
      country_code: "+33",
    },
    {
      name: "Gabon",
      slug: "gabon",
      country_code: "+241",
    },
    {
      name: "Gambia",
      slug: "gambia",
      country_code: "+220",
    },
    {
      name: "Georgia",
      slug: "georgia",
      country_code: "+995",
    },
    {
      name: "Germany",
      slug: "germany",
      country_code: "+49",
    },
    {
      name: "Ghana",
      slug: "ghana",
      country_code: "+233",
    },
    {
      name: "Greece",
      slug: "greece",
      country_code: "+30",
    },
    {
      name: "Grenada",
      slug: "grenada",
      country_code: "+1",
    },
    {
      name: "Guatemala",
      slug: "guatemala",
      country_code: "+502",
    },
    {
      name: "Guinea",
      slug: "guinea",
      country_code: "+224",
    },
    {
      name: "Guinea_Bissau",
      slug: "guinea_bissau",
      country_code: "+245",
    },
    {
      name: "Guyana",
      slug: "guyana",
      country_code: "+592",
    },
    {
      name: "Haiti",
      slug: "haiti",
      country_code: "+509",
    },
    {
      name: "Honduras",
      slug: "honduras",
      country_code: "+504",
    },
    {
      name: "Hungary",
      slug: "hungary",
      country_code: "+36",
    },
    {
      name: "Iceland",
      slug: "iceland",
      country_code: "+354",
    },
    {
      name: "India",
      slug: "india",
      country_code: "+91",
    },
    {
      name: "Indonesia",
      slug: "indonesia",
      country_code: "+62",
    },
    {
      name: "Iran",
      slug: "iran",
      country_code: "+98",
    },
    {
      name: "Iraq",
      slug: "iraq",
      country_code: "+964",
    },
    {
      name: "Ireland",
      slug: "ireland",
      country_code: "+353",
    },
    {
      name: "Israel",
      slug: "israel",
      country_code: "+972",
    },
    {
      name: "Italy",
      slug: "italy",
      country_code: "+39",
    },
    {
      name: "Jamaica",
      slug: "jamaica",
      country_code: "+1",
    },
    {
      name: "Japan",
      slug: "japan",
      country_code: "+81",
    },
    {
      name: "Jordan",
      slug: "jordan",
      country_code: "+962",
    },
    {
      name: "Kazakhstan",
      slug: "kazakhstan",
      country_code: "+7",
    },
    {
      name: "Kenya",
      slug: "kenya",
      country_code: "+254",
    },
    {
      name: "Kiribati",
      slug: "kiribati",
      country_code: "+686",
    },
    {
      name: "North Korea",
      slug: "north_korea",
      country_code: "+850",
    },
    {
      name: "South Korea",
      slug: "south_korea",
      country_code: "+82",
    },
    {
      name: "Kosovo",
      slug: "kosovo",
      country_code: "+383",
    },
    {
      name: "Kuwait",
      slug: "kuwait",
      country_code: "+965",
    },
    {
      name: "Kyrgyzstan",
      slug: "kyrgyzstan",
      country_code: "+996",
    },
    {
      name: "Laos",
      slug: "laos",
      country_code: "+856",
    },
    {
      name: "Latvia",
      slug: "latvia",
      country_code: "+371",
    },
    {
      name: "Lebanon",
      slug: "lebanon",
      country_code: "+961",
    },
    {
      name: "Lesotho",
      slug: "lesotho",
      country_code: "+266",
    },
    {
      name: "Liberia",
      slug: "liberia",
      country_code: "+231",
    },
    {
      name: "Libya",
      slug: "libya",
      country_code: "+218",
    },
    {
      name: "Liechtenstein",
      slug: "liechtenstein",
      country_code: "+423",
    },
    {
      name: "Lithuania",
      slug: "lithuania",
      country_code: "+370",
    },
    {
      name: "Luxembourg",
      slug: "luxembourg",
      country_code: "+352",
    },
    {
      name: "Madagascar",
      slug: "madagascar",
      country_code: "+261",
    },
    {
      name: "Malawi",
      slug: "malawi",
      country_code: "+265",
    },
    {
      name: "Malaysia",
      slug: "malaysia",
      country_code: "+60",
    },
    {
      name: "Maldives",
      slug: "maldives",
      country_code: "+960",
    },
    {
      name: "Mali",
      slug: "mali",
      country_code: "+223",
    },
    {
      name: "Malta",
      slug: "malta",
      country_code: "+356",
    },
    {
      name: "Marshall Islands",
      slug: "marshall_islands",
      country_code: "+692",
    },
    {
      name: "Mauritania",
      slug: "mauritania",
      country_code: "+222",
    },
    {
      name: "Mauritius",
      slug: "mauritius",
      country_code: "+230",
    },
    {
      name: "Mexico",
      slug: "mexico",
      country_code: "+52",
    },
    {
      name: "Micronesia",
      slug: "micronesia",
      country_code: "+691",
    },
    {
      name: "Moldova",
      slug: "moldova",
      country_code: "+373",
    },
    {
      name: "Monaco",
      slug: "monaco",
      country_code: "+377",
    },
    {
      name: "Mongolia",
      slug: "mongolia",
      country_code: "+976",
    },
    {
      name: "Montenegro",
      slug: "montenegro",
      country_code: "+382",
    },
    {
      name: "Morocco",
      slug: "morocco",
      country_code: "+212",
    },
    {
      name: "Mozambique",
      slug: "mozambique",
      country_code: "+258",
    },
    {
      name: "Myanmar",
      slug: "myanmar",
      country_code: "+95",
    },
    {
      name: "Namibia",
      slug: "namibia",
      country_code: "+264",
    },
    {
      name: "Nauru",
      slug: "nauru",
      country_code: "+674",
    },
    {
      name: "Nepal",
      slug: "nepal",
      country_code: "+977",
    },
    {
      name: "Netherlands",
      slug: "netherlands",
      country_code: "+31",
    },
    {
      name: "New Zealand",
      slug: "new_zealand",
      country_code: "+64",
    },
    {
      name: "Nicaragua",
      slug: "nicaragua",
      country_code: "+505",
    },
    {
      name: "Niger",
      slug: "niger",
      country_code: "+227",
    },
    {
      name: "Nigeria",
      slug: "nigeria",
      country_code: "+234",
    },
    {
      name: "North Macedonia",
      slug: "north_macedonia",
      country_code: "+389",
    },
    {
      name: "Norway",
      slug: "norway",
      country_code: "+47",
    },
    {
      name: "Oman",
      slug: "oman",
      country_code: "+968",
    },
    {
      name: "Pakistan",
      slug: "pakistan",
      country_code: "+92",
    },
    {
      name: "Palau",
      slug: "palau",
      country_code: "+680",
    },
    {
      name: "Palestine",
      slug: "palestine",
      country_code: "+970",
    },
    {
      name: "Panama",
      slug: "panama",
      country_code: "+507",
    },
    {
      name: "Papua New Guinea",
      slug: "papua_new_guinea",
      country_code: "+675",
    },
    {
      name: "Paraguay",
      slug: "paraguay",
      country_code: "+595",
    },
    {
      name: "Peru",
      slug: "peru",
      country_code: "+51",
    },
    {
      name: "Philippines",
      slug: "philippines",
      country_code: "+63",
    },
    {
      name: "Poland",
      slug: "poland",
      country_code: "+48",
    },
    {
      name: "Portugal",
      slug: "portugal",
      country_code: "+351",
    },
    {
      name: "Qatar",
      slug: "qatar",
      country_code: "+974",
    },
    {
      name: "Romania",
      slug: "romania",
      country_code: "+40",
    },
    {
      name: "Russia",
      slug: "russia",
      country_code: "+7",
    },
    {
      name: "Rwanda",
      slug: "rwanda",
      country_code: "+250",
    },
    {
      name: "Saint Kitts and Nevis",
      slug: "saint_kitts_and_nevis",
      country_code: "+1",
    },
    {
      name: "Saint Lucia",
      slug: "saint_lucia",
      country_code: "+1",
    },
    {
      name: "Saint Vincent and the Grenadines",
      slug: "saint_vincent_and_the_grenadines",
      country_code: "+1",
    },
    {
      name: "Samoa",
      slug: "samoa",
      country_code: "+685",
    },
    {
      name: "San Marino",
      slug: "san_marino",
      country_code: "+378",
    },
    {
      name: "Sao Tome and Principe",
      slug: "sao_tome_and_principe",
      country_code: "+239",
    },
    {
      name: "Saudi Arabia",
      slug: "saudi_arabia",
      country_code: "+966",
    },
    {
      name: "Senegal",
      slug: "senegal",
      country_code: "+221",
    },
    {
      name: "Serbia",
      slug: "serbia",
      country_code: "+381",
    },
    {
      name: "Seychelles",
      slug: "seychelles",
      country_code: "+248",
    },
    {
      name: "Sierra Leone",
      slug: "sierra_leone",
      country_code: "+232",
    },
    {
      name: "Singapore",
      slug: "singapore",
      country_code: "+65",
    },
    {
      name: "Slovakia",
      slug: "slovakia",
      country_code: "+421",
    },
    {
      name: "Slovenia",
      slug: "slovenia",
      country_code: "+386",
    },
    {
      name: "Solomon Islands",
      slug: "solomon_islands",
      country_code: "+677",
    },
    {
      name: "Somalia",
      slug: "somalia",
      country_code: "+252",
    },
    {
      name: "South Africa",
      slug: "south_africa",
      country_code: "+27",
    },
    {
      name: "South Sudan",
      slug: "south_sudan",
      country_code: "+211",
    },
    {
      name: "Spain",
      slug: "spain",
      country_code: "+34",
    },
    {
      name: "Sri Lanka",
      slug: "sri_lanka",
      country_code: "+94",
    },
    {
      name: "Sudan",
      slug: "sudan",
      country_code: "+249",
    },
    {
      name: "Suriname",
      slug: "suriname",
      country_code: "+597",
    },
    {
      name: "Sweden",
      slug: "sweden",
      country_code: "+46",
    },
    {
      name: "Switzerland",
      slug: "switzerland",
      country_code: "+41",
    },
    {
      name: "Syria",
      slug: "syria",
      country_code: "+963",
    },
    {
      name: "Taiwan",
      slug: "taiwan",
      country_code: "+886",
    },
    {
      name: "Tajikistan",
      slug: "tajikistan",
      country_code: "+992",
    },
    {
      name: "Tanzania",
      slug: "tanzania",
      country_code: "+255",
    },
    {
      name: "Thailand",
      slug: "thailand",
      country_code: "+66",
    },
    {
      name: "Timor-Leste",
      slug: "timor_leste",
      country_code: "+670",
    },
    {
      name: "Togo",
      slug: "togo",
      country_code: "+228",
    },
    {
      name: "Tonga",
      slug: "tonga",
      country_code: "+676",
    },
    {
      name: "Trinidad and Tobago",
      slug: "trinidad_and_tobago",
      country_code: "+1",
    },
    {
      name: "Tunisia",
      slug: "tunisia",
      country_code: "+216",
    },
    {
      name: "Turkey",
      slug: "turkey",
      country_code: "+90",
    },
    {
      name: "Turkmenistan",
      slug: "turkmenistan",
      country_code: "+993",
    },
    {
      name: "Tuvalu",
      slug: "tuvalu",
      country_code: "+688",
    },
    {
      name: "Uganda",
      slug: "uganda",
      country_code: "+256",
    },
    {
      name: "Ukraine",
      slug: "ukraine",
      country_code: "+380",
    },
    {
      name: "United Arab Emirates",
      slug: "united_arab_emirates",
      country_code: "+971",
    },
    {
      name: "United Kingdom",
      slug: "united_kingdom",
      country_code: "+44",
    },
    {
      name: "United States",
      slug: "united_states",
      country_code: "+1",
    },
    {
      name: "Uruguay",
      slug: "uruguay",
      country_code: "+598",
    },
    {
      name: "Uzbekistan",
      slug: "uzbekistan",
      country_code: "+998",
    },
    {
      name: "Vanuatu",
      slug: "vanuatu",
      country_code: "+678",
    },
    {
      name: "Vatican City",
      slug: "vatican_city",
      country_code: "+379",
    },
    {
      name: "Venezuela",
      slug: "venezuela",
      country_code: "+58",
    },
    {
      name: "Vietnam",
      slug: "vietnam",
      country_code: "+84",
    },
    {
      name: "Yemen",
      slug: "yemen",
      country_code: "+967",
    },
    {
      name: "Zambia",
      slug: "zambia",
      country_code: "+260",
    },
    {
      name: "Zimbabwe",
      slug: "zimbabwe",
      country_code: "+263",
    },
  ];
};

export default CountryList;

export const countriesWithCities = [
  {
    label: "Afghanistan",
    value: "afghanistan",
    cities: {
      city1: { value: "kabul", label: "Kabul" },
      city2: { value: "herat", label: "Herat" },
      city3: { value: "kandahar", label: "Kandahar" },
      city4: { value: "mazar_i_sharif", label: "Mazar-i-Sharif" },
      city5: { value: "jalalabad", label: "Jalalabad" },
    },
  },
  {
    label: "Albania",
    value: "albania",
    cities: {
      city1: { value: "tirana", label: "Tirana" },
      city2: { value: "durres", label: "Durres" },
      city3: { value: "vlore", label: "Vlore" },
      city4: { value: "shkoder", label: "Shkoder" },
      city5: { value: "elbasan", label: "Elbasan" },
    },
  },
  {
    label: "Algeria",
    value: "algeria",
    cities: {
      city1: { value: "algiers", label: "Algiers" },
      city2: { value: "oran", label: "Oran" },
      city3: { value: "constantine", label: "Constantine" },
      city4: { value: "annaba", label: "Annaba" },
      city5: { value: "blida", label: "Blida" },
    },
  },
  {
    label: "Andorra",
    value: "andorra",
    cities: {
      city1: { value: "andorra_la_vella", label: "Andorra la Vella" },
      city2: { value: "escaldes_engordany", label: "Escaldes-Engordany" },
      city3: { value: "encamp", label: "Encamp" },
      city4: { value: "canillo", label: "Canillo" },
      city5: { value: "la_massana", label: "La Massana" },
    },
  },
  {
    label: "Angola",
    value: "angola",
    cities: {
      city1: { value: "luanda", label: "Luanda" },
      city2: { value: "lobito", label: "Lobito" },
      city3: { value: "huambo", label: "Huambo" },
      city4: { value: "benguela", label: "Benguela" },
      city5: { value: "kuito", label: "Kuito" },
    },
  },
  {
    label: "Antigua and Barbuda",
    value: "antigua_and_barbuda",
    cities: {
      city1: { value: "saint_johns", label: "Saint John's" },
      city2: { value: "bolans", label: "Bolans" },
      city3: { value: "parham", label: "Parham" },
      city4: { value: "all_saints", label: "All Saints" },
      city5: { value: "liberta", label: "Liberta" },
    },
  },
  {
    label: "Argentina",
    value: "argentina",
    cities: {
      city1: { value: "buenos_aires", label: "Buenos Aires" },
      city2: { value: "cordoba", label: "Cordoba" },
      city3: { value: "rosario", label: "Rosario" },
      city4: { value: "mendoza", label: "Mendoza" },
      city5: { value: "san_miguel_de_tucuman", label: "San Miguel de Tucuman" },
    },
  },
  {
    label: "Armenia",
    value: "armenia",
    cities: {
      city1: { value: "yerevan", label: "Yerevan" },
      city2: { value: "gyumri", label: "Gyumri" },
      city3: { value: "vanadzor", label: "Vanadzor" },
      city4: { value: "vardavar", label: "Vardavar" },
      city5: { value: "artashat", label: "Artashat" },
    },
  },
  {
    label: "Australia",
    value: "australia",
    cities: {
      city1: { value: "sydney", label: "Sydney" },
      city2: { value: "melbourne", label: "Melbourne" },
      city3: { value: "brisbane", label: "Brisbane" },
      city4: { value: "perth", label: "Perth" },
      city5: { value: "adelaide", label: "Adelaide" },
    },
  },
  {
    label: "Austria",
    value: "austria",
    cities: {
      city1: { value: "vienna", label: "Vienna" },
      city2: { value: "graz", label: "Graz" },
      city3: { value: "linz", label: "Linz" },
      city4: { value: "salzburg", label: "Salzburg" },
      city5: { value: "innsbruck", label: "Innsbruck" },
    },
  },
  {
    label: "Azerbaijan",
    value: "azerbaijan",
    cities: {
      city1: { value: "baku", label: "Baku" },
      city2: { value: "ganja", label: "Ganja" },
      city3: { value: "sumqayit", label: "Sumqayit" },
      city4: { value: "mingachevir", label: "Mingachevir" },
      city5: { value: "lankaran", label: "Lankaran" },
    },
  },
  {
    label: "Bahamas",
    value: "bahamas",
    cities: {
      city1: { value: "nassau", label: "Nassau" },
      city2: { value: "freeport", label: "Freeport" },
      city3: { value: "grand_bahama", label: "Grand Bahama" },
      city4: { value: "abaco_island", label: "Abaco Island" },
      city5: { value: "andros_town", label: "Andros Town" },
    },
  },
  {
    label: "Bahrain",
    value: "bahrain",
    cities: {
      city1: { value: "manama", label: "Manama" },
      city2: { value: "muharraq", label: "Muharraq" },
      city3: { value: "hamad_town", label: "Hamad Town" },
      city4: { value: "rifaa", label: "Rifaa" },
      city5: { value: "isa_town", label: "Isa Town" },
    },
  },
  {
    label: "Bangladesh",
    value: "bangladesh",
    cities: {
      city1: { value: "dhaka", label: "Dhaka" },
      city2: { value: "chittagong", label: "Chittagong" },
      city3: { value: "khulna", label: "Khulna" },
      city4: { value: "rajshahi", label: "Rajshahi" },
      city5: { value: "comilla", label: "Comilla" },
    },
  },
  {
    label: "Barbados",
    value: "barbados",
    cities: {
      city1: { value: "bridgetown", label: "Bridgetown" },
      city2: { value: "speightstown", label: "Speightstown" },
      city3: { value: "oistins", label: "Oistins" },
      city4: { value: "bathsheba", label: "Bathsheba" },
      city5: { value: "holetown", label: "Holetown" },
    },
  },
  {
    label: "Belarus",
    value: "belarus",
    cities: {
      city1: { value: "minsk", label: "Minsk" },
      city2: { value: "gomel", label: "Gomel" },
      city3: { value: "mogilev", label: "Mogilev" },
      city4: { value: "vitebsk", label: "Vitebsk" },
      city5: { value: "hrodna", label: "Hrodna" },
    },
  },
  {
    label: "Belgium",
    value: "belgium",
    cities: {
      city1: { value: "brussels", label: "Brussels" },
      city2: { value: "antwerp", label: "Antwerp" },
      city3: { value: "ghent", label: "Ghent" },
      city4: { value: "charleroi", label: "Charleroi" },
      city5: { value: "liege", label: "Liege" },
    },
  },
  {
    label: "Belize",
    value: "belize",
    cities: {
      city1: { value: "belmopan", label: "Belmopan" },
      city2: { value: "belize_city", label: "Belize City" },
      city3: { value: "san_ignacio", label: "San Ignacio" },
      city4: { value: "orange_walk_town", label: "Orange Walk Town" },
      city5: { value: "dangriga", label: "Dangriga" },
    },
  },
  {
    label: "Benin",
    value: "benin",
    cities: {
      city1: { value: "porto_novo", label: "Porto-Novo" },
      city2: { value: "cotonou", label: "Cotonou" },
      city3: { value: "parakou", label: "Parakou" },
      city4: { value: "bohicon", label: "Bohicon" },
      city5: { value: "kandi", label: "Kandi" },
    },
  },
  {
    label: "Bhutan",
    value: "bhutan",
    cities: {
      city1: { value: "thimphu", label: "Thimphu" },
      city2: { value: "phuntsholing", label: "Phuntsholing" },
      city3: { value: "punakha", label: "Punakha" },
      city4: { value: "wangdue_phodrang", label: "Wangdue Phodrang" },
      city5: { value: "paro", label: "Paro" },
    },
  },
  {
    label: "Bolivia",
    value: "bolivia",
    cities: {
      city1: { value: "sucre", label: "Sucre" },
      city2: { value: "la_paz", label: "La Paz" },
      city3: { value: "santa_cruz", label: "Santa Cruz" },
      city4: { value: "cochabamba", label: "Cochabamba" },
      city5: { value: "oruro", label: "Oruro" },
    },
  },
  {
    label: "Bosnia and Herzegovina",
    value: "bosnia_and_herzegovina",
    cities: {
      city1: { value: "sarajevo", label: "Sarajevo" },
      city2: { value: "banja_luka", label: "Banja Luka" },
      city3: { value: "zenica", label: "Zenica" },
      city4: { value: "tuzla", label: "Tuzla" },
      city5: { value: "mostar", label: "Mostar" },
    },
  },
  {
    label: "Botswana",
    value: "botswana",
    cities: {
      city1: { value: "gaborone", label: "Gaborone" },
      city2: { value: "francistown", label: "Francistown" },
      city3: { value: "molepolole", label: "Molepolole" },
      city4: { value: "serowe", label: "Serowe" },
      city5: { value: "selibe_phikwe", label: "Selibe Phikwe" },
    },
  },
  {
    label: "Brazil",
    value: "brazil",
    cities: {
      city1: { value: "brasilia", label: "Brasilia" },
      city2: { value: "sao_paulo", label: "Sao Paulo" },
      city3: { value: "rio_de_janeiro", label: "Rio de Janeiro" },
      city4: { value: "salvador", label: "Salvador" },
      city5: { value: "fortaleza", label: "Fortaleza" },
    },
  },
  {
    label: "Brunei",
    value: "brunei",
    cities: {
      city1: { value: "bandar_seri_begawan", label: "Bandar Seri Begawan" },
      city2: { value: "kuala_belait", label: "Kuala Belait" },
      city3: { value: "seria", label: "Seria" },
      city4: { value: "tutong", label: "Tutong" },
      city5: { value: "bangar", label: "Bangar" },
    },
  },
  {
    label: "Bulgaria",
    value: "bulgaria",
    cities: {
      city1: { value: "sofia", label: "Sofia" },
      city2: { value: "plovdiv", label: "Plovdiv" },
      city3: { value: "varna", label: "Varna" },
      city4: { value: "burgas", label: "Burgas" },
      city5: { value: "rousse", label: "Rousse" },
    },
  },
  {
    label: "Burkina Faso",
    value: "burkina_faso",
    cities: {
      city1: { value: "ouagadougou", label: "Ouagadougou" },
      city2: { value: "bobodioulasso", label: "Bobodioulasso" },
      city3: { value: "koudougou", label: "Koudougou" },
      city4: { value: "banfora", label: "Banfora" },
      city5: { value: "dori", label: "Dori" },
    },
  },
  {
    label: "Burundi",
    value: "burundi",
    cities: {
      city1: { value: "bujumbura", label: "Bujumbura" },
      city2: { value: "gitega", label: "Gitega" },
      city3: { value: "muyinga", label: "Muyinga" },
      city4: { value: "rumonge", label: "Rumonge" },
      city5: { value: "ngozi", label: "Ngozi" },
    },
  },
  {
    label: "Cambodia",
    value: "cambodia",
    cities: {
      city1: { value: "phnom_penh", label: "Phnom Penh" },
      city2: { value: "siem_reap", label: "Siem Reap" },
      city3: { value: "battambang", label: "Battambang" },
      city4: { value: "sihanoukville", label: "Sihanoukville" },
      city5: { value: "poipet", label: "Poipet" },
    },
  },
  {
    label: "Cameroon",
    value: "cameroon",
    cities: {
      city1: { value: "yaounde", label: "Yaounde" },
      city2: { value: "douala", label: "Douala" },
      city3: { value: "garoua", label: "Garoua" },
      city4: { value: "bamenda", label: "Bamenda" },
      city5: { value: "maroua", label: "Maroua" },
    },
  },
  {
    label: "Canada",
    value: "canada",
    cities: {
      city1: { value: "ottawa", label: "Ottawa" },
      city2: { value: "toronto", label: "Toronto" },
      city3: { value: "montreal", label: "Montreal" },
      city4: { value: "vancouver", label: "Vancouver" },
      city5: { value: "calgary", label: "Calgary" },
    },
  },
  {
    label: "Cape Verde",
    value: "cape_verde",
    cities: {
      city1: { value: "praia", label: "Praia" },
      city2: { value: "mindelo", label: "Mindelo" },
      city3: { value: "santa_maria", label: "Santa Maria" },
      city4: { value: "assomada", label: "Assomada" },
      city5: { value: "sal_rei", label: "Sal Rei" },
    },
  },
  {
    label: "Central African Republic",
    value: "central_african_republic",
    cities: {
      city1: { value: "bangui", label: "Bangui" },
      city2: { value: "bimbo", label: "Bimbo" },
      city3: { value: "berberati", label: "Berberati" },
      city4: { value: "carnot", label: "Carnot" },
      city5: { value: "bambari", label: "Bambari" },
    },
  },
  {
    label: "Chad",
    value: "chad",
    cities: {
      city1: { value: "ndjamena", label: "N'Djamena" },
      city2: { value: "moundou", label: "Moundou" },
      city3: { value: "sagh", label: "Sagh" },
      city4: { value: "abche", label: "Abche" },
      city5: { value: "fada", label: "Fada" },
    },
  },
  {
    label: "Chile",
    value: "chile",
    cities: {
      city1: { value: "santiago", label: "Santiago" },
      city2: { value: "valparaiso", label: "Valparaiso" },
      city3: { value: "concepcion", label: "Concepcion" },
      city4: { value: "puente_alto", label: "Puente Alto" },
      city5: { value: "antofagasta", label: "Antofagasta" },
    },
  },
  {
    label: "China",
    value: "china",
    cities: {
      city1: { value: "beijing", label: "Beijing" },
      city2: { value: "shanghai", label: "Shanghai" },
      city3: { value: "guangzhou", label: "Guangzhou" },
      city4: { value: "shenzhen", label: "Shenzhen" },
      city5: { value: "chongqing", label: "Chongqing" },
    },
  },
  {
    label: "Colombia",
    value: "colombia",
    cities: {
      city1: { value: "bogota", label: "Bogota" },
      city2: { value: "medellin", label: "Medellin" },
      city3: { value: "cali", label: "Cali" },
      city4: { value: "barranquilla", label: "Barranquilla" },
      city5: { value: "cartagena", label: "Cartagena" },
    },
  },
  {
    label: "Comoros",
    value: "comoros",
    cities: {
      city1: { value: "moroni", label: "Moroni" },
      city2: { value: "mutsamudu", label: "Mutsamudu" },
      city3: { value: "fomboni", label: "Fomboni" },
      city4: { value: "domoni", label: "Domoni" },
      city5: { value: "sima", label: "Simaa" },
    },
  },
  {
    label: "Congo (Brazzaville)",
    value: "congo_brazzaville",
    cities: {
      city1: { value: "brazzaville", label: "Brazzaville" },
      city2: { value: "pointe_noire", label: "Pointe-Noire" },
      city3: { value: "dolisie", label: "Dolisie" },
      city4: { value: "kayes", label: "Kayes" },
      city5: { value: "owando", label: "Owando" },
    },
  },
  {
    label: "Congo (Kinshasa)",
    value: "congo_kinshasa",
    cities: {
      city1: { value: "kinshasa", label: "Kinshasa" },
      city2: { value: "lubumbashi", label: "Lubumbashi" },
      city3: { value: "mbuji_mayi", label: "Mbuji-Mayi" },
      city4: { value: "kisangani", label: "Kisangani" },
      city5: { value: "goma", label: "Goma" },
    },
  },
  {
    label: "Costa Rica",
    value: "costa_rica",
    cities: {
      city1: { value: "san_jose", label: "San Jose" },
      city2: { value: "limon", label: "Limon" },
      city3: { value: "san_francisco", label: "San Francisco" },
      city4: { value: "alajuela", label: "Alajuela" },
      city5: { value: "heredia", label: "Heredia" },
    },
  },
  {
    label: "Croatia",
    value: "croatia",
    cities: {
      city1: { value: "zagreb", label: "Zagreb" },
      city2: { value: "split", label: "Split" },
      city3: { value: "rijeka", label: "Rijeka" },
      city4: { value: "osijek", label: "Osijek" },
      city5: { value: "zadar", label: "Zadar" },
    },
  },
  {
    label: "Cuba",
    value: "cuba",
    cities: {
      city1: { value: "havana", label: "Havana" },
      city2: { value: "santiago_de_cuba", label: "Santiago de Cuba" },
      city3: { value: "camaguey", label: "Camaguey" },
      city4: { value: "holguin", label: "Holguin" },
      city5: { value: "guantanamo", label: "Guantanamo" },
    },
  },
  {
    label: "Cyprus",
    value: "cyprus",
    cities: {
      city1: { value: "nicosia", label: "Nicosia" },
      city2: { value: "limassol", label: "Limassol" },
      city3: { value: "larnaca", label: "Larnaca" },
      city4: { value: "paphos", label: "Paphos" },
      city5: { value: "famagusta", label: "Famagusta" },
    },
  },
  {
    label: "Czech Republic",
    value: "czech_republic",
    cities: {
      city1: { value: "prague", label: "Prague" },
      city2: { value: "brno", label: "Brno" },
      city3: { value: "ostrava", label: "Ostrava" },
      city4: { value: "plzen", label: "Plzen" },
      city5: { value: "liberec", label: "Liberec" },
    },
  },
  {
    label: "Denmark",
    value: "denmark",
    cities: {
      city1: { value: "copenhagen", label: "Copenhagen" },
      city2: { value: "aarhus", label: "Aarhus" },
      city3: { value: "odense", label: "Odense" },
      city4: { value: "aalborg", label: "Aalborg" },
      city5: { value: "esbjerg", label: "Esbjerg" },
    },
  },
  {
    label: "Djibouti",
    value: "djibouti",
    cities: {
      city1: { value: "djibouti_city", label: "Djibouti City" },
      city2: { value: "ali_sabieh", label: "Ali Sabieh" },
      city3: { value: "tadjoura", label: "Tadjoura" },
      city4: { value: "ouboui", label: "Ouboui" },
      city5: { value: "dikhil", label: "Dikhil" },
    },
  },
  {
    label: "Dominica",
    value: "dominica",
    cities: {
      city1: { value: "roseau", label: "Roseau" },
      city2: { value: "portsmouth", label: "Portsmouth" },
      city3: { value: "la_plaine", label: "La Plaine" },
      city4: { value: "berekua", label: "Berekua" },
      city5: { value: "mahaut", label: "Mahaut" },
    },
  },
  {
    label: "Dominican Republic",
    value: "dominican_republic",
    cities: {
      city1: { value: "santo_domingo", label: "Santo Domingo" },
      city2: { value: "santiago", label: "Santiago" },
      city3: { value: "santo_domingo_oeste", label: "Santo Domingo Oeste" },
      city4: { value: "santo_domingo_este", label: "Santo Domingo Este" },
      city5: { value: "santo_domingo_norte", label: "Santo Domingo Norte" },
    },
  },
  {
    label: "East Timor",
    value: "east_timor",
    cities: {
      city1: { value: "dili", label: "Dili" },
      city2: { value: "baucau", label: "Baucau" },
      city3: { value: "liquica", label: "Liquica" },
      city4: { value: "maubara", label: "Maubara" },
      city5: { value: "atambua", label: "Atambua" },
    },
  },
  {
    label: "Ecuador",
    value: "ecuador",
    cities: {
      city1: { value: "quito", label: "Quito" },
      city2: { value: "guayaquil", label: "Guayaquil" },
      city3: { value: "cuenca", label: "Cuenca" },
      city4: { value: "santo_domingo", label: "Santo Domingo" },
      city5: { value: "machala", label: "Machala" },
    },
  },
  {
    label: "Egypt",
    value: "egypt",
    cities: {
      city1: { value: "cairo", label: "Cairo" },
      city2: { value: "alexandria", label: "Alexandria" },
      city3: { value: "giza", label: "Giza" },
      city4: { value: "shubra_el_kheima", label: "Shubra El Kheima" },
      city5: { value: "port_said", label: "Port Said" },
    },
  },
  {
    label: "El Salvador",
    value: "el_salvador",
    cities: {
      city1: { value: "san_salvador", label: "San Salvador" },
      city2: { value: "santa_ana", label: "Santa Ana" },
      city3: { value: "san_miguel", label: "San Miguel" },
      city4: { value: "santa_tecla", label: "Santa Tecla" },
      city5: { value: "apopa", label: "Apopa" },
    },
  },
  {
    label: "Equatorial Guinea",
    value: "equatorial_guinea",
    cities: {
      city1: { value: "malabo", label: "Malabo" },
      city2: { value: "bata", label: "Bata" },
      city3: { value: "eseniora", label: "Eseniora" },
      city4: { value: "ebandja", label: "Ebandja" },
      city5: { value: "micomeseng", label: "Micomeseng" },
    },
  },
  {
    label: "Eritrea",
    value: "eritrea",
    cities: {
      city1: { value: "asmara", label: "Asmara" },
      city2: { value: "massawa", label: "Massawa" },
      city3: { value: "keren", label: "Keren" },
      city4: { value: "assab", label: "Assab" },
      city5: { value: "mek'ele", label: "Mek'ele" },
    },
  },
  {
    label: "Estonia",
    value: "estonia",
    cities: {
      city1: { value: "tallinn", label: "Tallinn" },
      city2: { value: "tartu", label: "Tartu" },
      city3: { value: "narva", label: "Narva" },
      city4: { value: "kohtla_jarve", label: "Kohtla-Jarve" },
      city5: { value: "parnu", label: "Parnu" },
    },
  },
  {
    label: "Ethiopia",
    value: "ethiopia",
    cities: {
      city1: { value: "addis_ababa", label: "Addis Ababa" },
      city2: { value: "dire_dawa", label: "Dire Dawa" },
      city3: { value: "mombasa", label: "Mombasa" },
      city4: { value: "hawassa", label: "Hawassa" },
      city5: { value: "jima", label: "Jima" },
    },
  },
  {
    label: "Fiji",
    value: "fiji",
    cities: {
      city1: { value: "suva", label: "Suva" },
      city2: { value: "lautoka", label: "Lautoka" },
      city3: { value: "nadi", label: "Nadi" },
      city4: { value: "labasa", label: "Labasa" },
      city5: { value: "ba", label: "Ba" },
    },
  },
  {
    label: "Finland",
    value: "finland",
    cities: {
      city1: { value: "helsinki", label: "Helsinki" },
      city2: { value: "espoo", label: "Espoo" },
      city3: { value: "tampere", label: "Tampere" },
      city4: { value: "vantaa", label: "Vantaa" },
      city5: { value: "turku", label: "Turku" },
    },
  },
  {
    label: "France",
    value: "france",
    cities: {
      city1: { value: "paris", label: "Paris" },
      city2: { value: "marseille", label: "Marseille" },
      city3: { value: "lyon", label: "Lyon" },
      city4: { value: "toulouse", label: "Toulouse" },
      city5: { value: "nice", label: "Nice" },
    },
  },
  {
    label: "Gabon",
    value: "gabon",
    cities: {
      city1: { value: "libreville", label: "Libreville" },
      city2: { value: "port_gentil", label: "Port-Gentil" },
      city3: { value: "masuku", label: "Masuku" },
      city4: { value: "oyem", label: "Oyem" },
      city5: { value: "mouila", label: "Mouila" },
    },
  },
  {
    label: "Gambia",
    value: "gambia",
    cities: {
      city1: { value: "banjul", label: "Banjul" },
      city2: { value: "serekunda", label: "Serekunda" },
      city3: { value: "brikama", label: "Brikama" },
      city4: { value: "bakau", label: "Bakau" },
      city5: { value: "lamin", label: "Lamin" },
    },
  },
  {
    label: "Georgia",
    value: "georgia",
    cities: {
      city1: { value: "tbilisi", label: "Tbilisi" },
      city2: { value: "kutaisi", label: "Kutaisi" },
      city3: { value: "batumi", label: "Batumi" },
      city4: { value: "rustavi", label: "Rustavi" },
      city5: { value: "zugdidi", label: "Zugdidi" },
    },
  },
  {
    label: "Germany",
    value: "germany",
    cities: {
      city1: { value: "berlin", label: "Berlin" },
      city2: { value: "hamburg", label: "Hamburg" },
      city3: { value: "munich", label: "Munich" },
      city4: { value: "cologne", label: "Cologne" },
      city5: { value: "frankfurt", label: "Frankfurt" },
    },
  },
  {
    label: "Ghana",
    value: "ghana",
    cities: {
      city1: { value: "accra", label: "Accra" },
      city2: { value: "kumasi", label: "Kumasi" },
      city3: { value: "tamale", label: "Tamale" },
      city4: { value: "takoradi", label: "Takoradi" },
      city5: { value: "achiase", label: "Achiase" },
    },
  },
  {
    label: "Greece",
    value: "greece",
    cities: {
      city1: { value: "athens", label: "Athens" },
      city2: { value: "thessaloniki", label: "Thessaloniki" },
      city3: { value: "patra", label: "Patra" },
      city4: { value: "heraklion", label: "Heraklion" },
      city5: { value: "larissa", label: "Larissa" },
    },
  },
  {
    label: "Grenada",
    value: "grenada",
    cities: {
      city1: { value: "st_george's", label: "St. George's" },
      city2: { value: "grenville", label: "Grenville" },
      city3: { value: "gouyave", label: "Gouyave" },
      city4: { value: "sauteurs", label: "Sauteurs" },
      city5: { value: "hillsborough", label: "Hillsborough" },
    },
  },
  {
    label: "Guatemala",
    value: "guatemala",
    cities: {
      city1: { value: "guatemala_city", label: "Guatemala City" },
      city2: { value: "mixco", label: "Mixco" },
      city3: { value: "villa_nueva", label: "Villa Nueva" },
      city4: { value: "quetzaltenango", label: "Quetzaltenango" },
      city5: { value: "escuintla", label: "Escuintla" },
    },
  },
  {
    label: "Guinea",
    value: "guinea",
    cities: {
      city1: { value: "conakry", label: "Conakry" },
      city2: { value: "n_zerekore", label: "N'Zerekore" },
      city3: { value: "boke", label: "Boke" },
      city4: { value: "kindia", label: "Kindia" },
      city5: { value: "kankan", label: "Kankan" },
    },
  },
  {
    label: "Guinea-Bissau",
    value: "guinea_bissau",
    cities: {
      city1: { value: "bissau", label: "Bissau" },
      city2: { value: "bafata", label: "Bafata" },
      city3: { value: "cacheu", label: "Cacheu" },
      city4: { value: "bissora", label: "Bissora" },
      city5: { value: "farim", label: "Farim" },
    },
  },
  {
    label: "Guyana",
    value: "guyana",
    cities: {
      city1: { value: "georgetown", label: "Georgetown" },
      city2: { value: "linden", label: "Linden" },
      city3: { value: "new_amsterdam", label: "New Amsterdam" },
      city4: { value: "barts_town", label: "Bart's Town" },
      city5: { value: "rosignol", label: "Rosignol" },
    },
  },
  {
    label: "Haiti",
    value: "haiti",
    cities: {
      city1: { value: "port_au_prince", label: "Port-au-Prince" },
      city2: { value: "carrefour", label: "Carrefour" },
      city3: { value: "delmas", label: "Delmas" },
      city4: { value: "cap_haitien", label: "Cap-Haitien" },
      city5: { value: "petionville", label: "Petionville" },
    },
  },
  {
    label: "Honduras",
    value: "honduras",
    cities: {
      city1: { value: "tegucigalpa", label: "Tegucigalpa" },
      city2: { value: "san_pedro_sula", label: "San Pedro Sula" },
      city3: { value: "choloma", label: "Choloma" },
      city4: { value: "la_ceiba", label: "La Ceiba" },
      city5: { value: "el_progreso", label: "El Progreso" },
    },
  },
  {
    label: "Hungary",
    value: "hungary",
    cities: {
      city1: { value: "budapest", label: "Budapest" },
      city2: { value: "debrecen", label: "Debrecen" },
      city3: { value: "szeged", label: "Szeged" },
      city4: { value: "miskolc", label: "Miskolc" },
      city5: { value: "pecs", label: "Pecs" },
    },
  },
  {
    label: "Iceland",
    value: "iceland",
    cities: {
      city1: { value: "reykjavik", label: "Reykjavik" },
      city2: { value: "kopavogur", label: "Kopavogur" },
      city3: { value: "hafnarfjordur", label: "Hafnarfjordur" },
      city4: { value: "akureyri", label: "Akureyri" },
      city5: { value: "keflavik", label: "Keflavik" },
    },
  },
  {
    label: "India",
    value: "india",
    cities: {
      city1: { value: "mumbai", label: "Mumbai" },
      city2: { value: "delhi", label: "Delhi" },
      city3: { value: "bangalore", label: "Bangalore" },
      city4: { value: "hyderabad", label: "Hyderabad" },
      city5: { value: "ahmedabad", label: "Ahmedabad" },
    },
  },
  {
    label: "Indonesia",
    value: "indonesia",
    cities: {
      city1: { value: "jakarta", label: "Jakarta" },
      city2: { value: "surabaya", label: "Surabaya" },
      city3: { value: "bandung", label: "Bandung" },
      city4: { value: "medan", label: "Medan" },
      city5: { value: "bekasi", label: "Bekasi" },
    },
  },
  {
    label: "Iran",
    value: "iran",
    cities: {
      city1: { value: "tehran", label: "Tehran" },
      city2: { value: "mashhad", label: "Mashhad" },
      city3: { value: "isfahan", label: "Isfahan" },
      city4: { value: "karaj", label: "Karaj" },
      city5: { value: "tabriz", label: "Tabriz" },
    },
  },
  {
    label: "Iraq",
    value: "iraq",
    cities: {
      city1: { value: "baghdad", label: "Baghdad" },
      city2: { value: "basra", label: "Basra" },
      city3: { value: "mosul", label: "Mosul" },
      city4: { value: "erbil", label: "Erbil" },
      city5: { value: "sulaymaniyah", label: "Sulaymaniyah" },
    },
  },
  {
    label: "Ireland",
    value: "ireland",
    cities: {
      city1: { value: "dublin", label: "Dublin" },
      city2: { value: "cork", label: "Cork" },
      city3: { value: "limerick", label: "Limerick" },
      city4: { value: "galway", label: "Galway" },
      city5: { value: "waterford", label: "Waterford" },
    },
  },
  {
    label: "Israel",
    value: "israel",
    cities: {
      city1: { value: "jerusalem", label: "Jerusalem" },
      city2: { value: "tel_aviv", label: "Tel Aviv" },
      city3: { value: "haifa", label: "Haifa" },
      city4: { value: "ashdod", label: "Ashdod" },
      city5: { value: "beer_sheva", label: "Beer Sheva" },
    },
  },
  {
    label: "Italy",
    value: "italy",
    cities: {
      city1: { value: "rome", label: "Rome" },
      city2: { value: "milan", label: "Milan" },
      city3: { value: "naples", label: "Naples" },
      city4: { value: "turin", label: "Turin" },
      city5: { value: "palermo", label: "Palermo" },
    },
  },
  {
    label: "Jamaica",
    value: "jamaica",
    cities: {
      city1: { value: "kingston", label: "Kingston" },
      city2: { value: "montego_bay", label: "Montego Bay" },
      city3: { value: "portmore", label: "Portmore" },
      city4: { value: "mandeville", label: "Mandeville" },
      city5: { value: "spanish_town", label: "Spanish Town" },
    },
  },
  {
    label: "Japan",
    value: "japan",
    cities: {
      city1: { value: "tokyo", label: "Tokyo" },
      city2: { value: "yokohama", label: "Yokohama" },
      city3: { value: "osaka", label: "Osaka" },
      city4: { value: "nagoya", label: "Nagoya" },
      city5: { value: "sapporo", label: "Sapporo" },
    },
  },
  {
    label: "Jordan",
    value: "jordan",
    cities: {
      city1: { value: "amman", label: "Amman" },
      city2: { value: "zarqa", label: "Zarqa" },
      city3: { value: "irbid", label: "Irbid" },
      city4: { value: "aqaba", label: "Aqaba" },
      city5: { value: "maan", label: "Ma'an" },
    },
  },
  // Countries starting with letter 'K'
  {
    label: "Kazakhstan",
    value: "kazakhstan",
    cities: {
      city1: { value: "almaty", label: "Almaty" },
      city2: { value: "nur_sultan", label: "Nur-Sultan" },
      city3: { value: "shymkent", label: "Shymkent" },
      city4: { value: "karagandy", label: "Karagandy" },
      city5: { value: "aktobe", label: "Aktobe" },
    },
  },
  {
    label: "Kenya",
    value: "kenya",
    cities: {
      city1: { value: "nairobi", label: "Nairobi" },
      city2: { value: "mombasa", label: "Mombasa" },
      city3: { value: "kisumu", label: "Kisumu" },
      city4: { value: "nakuru", label: "Nakuru" },
      city5: { value: "eldoret", label: "Eldoret" },
    },
  },
  {
    label: "Kiribati",
    value: "kiribati",
    cities: {
      city1: { value: "tarawa", label: "Tarawa" },
      city2: { value: "betio", label: "Betio" },
      city3: { value: "bikenibeu", label: "Bikenibeu" },
      city4: { value: "bairiki", label: "Bairiki" },
      city5: { value: "teaoraereke", label: "Teaoraereke" },
    },
  },
  {
    label: "Korea, North",
    value: "north_korea",
    cities: {
      city1: { value: "pyongyang", label: "Pyongyang" },
      city2: { value: "hamhung", label: "Hamhung" },
      city3: { value: "chongjin", label: "Chongjin" },
      city4: { value: "nampo", label: "Nampo" },
      city5: { value: "wonsan", label: "Wonsan" },
    },
  },
  {
    label: "Korea, South",
    value: "south_korea",
    cities: {
      city1: { value: "seoul", label: "Seoul" },
      city2: { value: "busan", label: "Busan" },
      city3: { value: "incheon", label: "Incheon" },
      city4: { value: "daegu", label: "Daegu" },
      city5: { value: "daejeon", label: "Daejeon" },
    },
  },
  {
    label: "Kosovo",
    value: "kosovo",
    cities: {
      city1: { value: "pristina", label: "Pristina" },
      city2: { value: "prizren", label: "Prizren" },
      city3: { value: "mitrovica", label: "Mitrovica" },
      city4: { value: "gjilan", label: "Gjilan" },
      city5: { value: "ferizaj", label: "Ferizaj" },
    },
  },
  {
    label: "Kuwait",
    value: "kuwait",
    cities: {
      city1: { value: "kuwait_city", label: "Kuwait City" },
      city2: { value: "al_ahmadi", label: "Al Ahmadi" },
      city3: { value: "hawalli", label: "Hawalli" },
      city4: { value: "farwaniya", label: "Farwaniya" },
      city5: { value: "jabriya", label: "Jabriya" },
    },
  },
  {
    label: "Kyrgyzstan",
    value: "kyrgyzstan",
    cities: {
      city1: { value: "bishkek", label: "Bishkek" },
      city2: { value: "osh", label: "Osh" },
      city3: { value: "jalal_abad", label: "Jalal-Abad" },
      city4: { value: "karakol", label: "Karakol" },
      city5: { value: "tokmok", label: "Tokmok" },
    },
  },
  // Countries starting with letter 'L'
  {
    label: "Laos",
    value: "laos",
    cities: {
      city1: { value: "vientiane", label: "Vientiane" },
      city2: { value: "luang_prabang", label: "Luang Prabang" },
      city3: { value: "pakse", label: "Pakse" },
      city4: { value: "savannakhet", label: "Savannakhet" },
      city5: { value: "luang_namtha", label: "Luang Namtha" },
    },
  },
  {
    label: "Latvia",
    value: "latvia",
    cities: {
      city1: { value: "riga", label: "Riga" },
      city2: { value: "daugavpils", label: "Daugavpils" },
      city3: { value: "liepaja", label: "Liepāja" },
      city4: { value: "jelgava", label: "Jelgava" },
      city5: { value: "jurmala", label: "Jūrmala" },
    },
  },
  {
    label: "Lebanon",
    value: "lebanon",
    cities: {
      city1: { value: "beirut", label: "Beirut" },
      city2: { value: "tripoli", label: "Tripoli" },
      city3: { value: "sidon", label: "Sidon" },
      city4: { value: "tyre", label: "Tyre" },
      city5: { value: "aalto", label: "Aalto" },
    },
  },
  {
    label: "Lesotho",
    value: "lesotho",
    cities: {
      city1: { value: "maseru", label: "Maseru" },
      city2: { value: "leribe", label: "Leribe" },
      city3: { value: "mohale's_hoek", label: "Mohale's Hoek" },
      city4: { value: "maseru", label: "Mafeteng" },
      city5: { value: "quthing", label: "Quthing" },
    },
  },
  {
    label: "Liberia",
    value: "liberia",
    cities: {
      city1: { value: "monrovia", label: "Monrovia" },
      city2: { value: "gbarnga", label: "Gbarnga" },
      city3: { value: "buchanan", label: "Buchanan" },
      city4: { value: "harper", label: "Harper" },
      city5: { value: "kakata", label: "Kakata" },
    },
  },
  {
    label: "Libya",
    value: "libya",
    cities: {
      city1: { value: "tripoli", label: "Tripoli" },
      city2: { value: "benghazi", label: "Benghazi" },
      city3: { value: "misrata", label: "Misrata" },
      city4: { value: "tarhuna", label: "Tarhuna" },
      city5: { value: "al_kufrah", label: "Al-Kufrah" },
    },
  },
  {
    label: "Liechtenstein",
    value: "liechtenstein",
    cities: {
      city1: { value: "vaduz", label: "Vaduz" },
      city2: { value: "schaan", label: "Schaan" },
      city3: { value: "triesen", label: "Triesen" },
      city4: { value: "eschen", label: "Eschen" },
      city5: { value: "balzers", label: "Balzers" },
    },
  },
  {
    label: "Lithuania",
    value: "lithuania",
    cities: {
      city1: { value: "vilnius", label: "Vilnius" },
      city2: { value: "kaunas", label: "Kaunas" },
      city3: { value: "klaipeda", label: "Klaipėda" },
      city4: { value: "siauliai", label: "Šiauliai" },
      city5: { value: "panevezys", label: "Panevėžys" },
    },
  },
  {
    label: "Luxembourg",
    value: "luxembourg",
    cities: {
      city1: { value: "luxembourg_city", label: "Luxembourg City" },
      city2: { value: "esch_sur_alzette", label: "Esch-sur-Alzette" },
      city3: { value: "differdange", label: "Differdange" },
      city4: { value: "dudelange", label: "Dudelange" },
      city5: { value: "ettelbruck", label: "Ettelbruck" },
    },
  },
  {
    label: "Madagascar",
    value: "madagascar",
    cities: {
      city1: { value: "antananarivo", label: "Antananarivo" },
      city2: { value: "toamasina", label: "Toamasina" },
      city3: { value: "antsohihy", label: "Antsohihy" },
      city4: { value: "antsirabe", label: "Antsirabe" },
      city5: { value: "mahajanga", label: "Mahajanga" },
    },
  },
  {
    label: "Malawi",
    value: "malawi",
    cities: {
      city1: { value: "lilongwe", label: "Lilongwe" },
      city2: { value: "blantyre", label: "Blantyre" },
      city3: { value: "mzuzu", label: "Mzuzu" },
      city4: { value: "zomba", label: "Zomba" },
      city5: { value: "kasungu", label: "Kasungu" },
    },
  },
  {
    label: "Malaysia",
    value: "malaysia",
    cities: {
      city1: { value: "kuala_lumpur", label: "Kuala Lumpur" },
      city2: { value: "george_town", label: "George Town" },
      city3: { value: "johor_bahru", label: "Johor Bahru" },
      city4: { value: "ipoh", label: "Ipoh" },
      city5: { value: "kuching", label: "Kuching" },
    },
  },
  {
    label: "Maldives",
    value: "maldives",
    cities: {
      city1: { value: "male", label: "Malé" },
      city2: { value: "addu_city", label: "Addu City" },
      city3: { value: "fuvahmulah_city", label: "Fuvahmulah City" },
      city4: { value: "hithadhoo", label: "Hithadhoo" },
      city5: { value: "kulhudhuffushi", label: "Kulhudhuffushi" },
    },
  },
  {
    label: "Mali",
    value: "mali",
    cities: {
      city1: { value: "bamako", label: "Bamako" },
      city2: { value: "sikasso", label: "Sikasso" },
      city3: { value: "mopti", label: "Mopti" },
      city4: { value: "segou", label: "Ségou" },
      city5: { value: "kayes", label: "Kayes" },
    },
  },
  {
    label: "Malta",
    value: "malta",
    cities: {
      city1: { value: "valletta", label: "Valletta" },
      city2: { value: "birkirkara", label: "Birkirkara" },
      city3: { value: "qormi", label: "Qormi" },
      city4: { value: "mosta", label: "Mosta" },
      city5: { value: "sliema", label: "Sliema" },
    },
  },
  {
    label: "Marshall Islands",
    value: "marshall_islands",
    cities: {
      city1: { value: "majuro", label: "Majuro" },
      city2: { value: "ebeye", label: "Ebeye" },
      city3: { value: "woja", label: "Woja" },
      city4: { value: "jabor", label: "Jabor" },
      city5: { value: "rikas", label: "Rikas" },
    },
  },
  {
    label: "Mauritania",
    value: "mauritania",
    cities: {
      city1: { value: "nouakchott", label: "Nouakchott" },
      city2: { value: "nouadhibou", label: "Nouadhibou" },
      city3: { value: "kiffa", label: "Kiffa" },
      city4: { value: "kaedi", label: "Kaedi" },
      city5: { value: "rosso", label: "Rosso" },
    },
  },
  {
    label: "Mauritius",
    value: "mauritius",
    cities: {
      city1: { value: "port_louis", label: "Port Louis" },
      city2: { value: "beau_bassin_rose_hill", label: "Beau Bassin-Rose Hill" },
      city3: { value: "vacoas_phoenix", label: "Vacoas-Phoenix" },
      city4: { value: "curepipe", label: "Curepipe" },
      city5: { value: "quatre_bornes", label: "Quatre Bornes" },
    },
  },
  {
    label: "Mexico",
    value: "mexico",
    cities: {
      city1: { value: "mexico_city", label: "Mexico City" },
      city2: { value: "guadalajara", label: "Guadalajara" },
      city3: { value: "monterrey", label: "Monterrey" },
      city4: { value: "puebla", label: "Puebla" },
      city5: { value: "tijuana", label: "Tijuana" },
    },
  },
  {
    label: "Micronesia",
    value: "micronesia",
    cities: {
      city1: { value: "palikir", label: "Palikir" },
      city2: { value: "kolonia", label: "Kolonia" },
      city3: { value: "weno", label: "Weno" },
      city4: { value: "uwajima", label: "Uwajima" },
      city5: { value: "tomoa", label: "Tomoa" },
    },
  },
  {
    label: "Moldova",
    value: "moldova",
    cities: {
      city1: { value: "chisinau", label: "Chisinau" },
      city2: { value: "tiraspol", label: "Tiraspol" },
      city3: { value: "balti", label: "Balti" },
      city4: { value: "bender", label: "Bender" },
      city5: { value: "ribnita", label: "Ribnita" },
    },
  },
  {
    label: "Monaco",
    value: "monaco",
    cities: {
      city1: { value: "monaco", label: "Monaco" },
      city2: { value: "monte_carlo", label: "Monte-Carlo" },
      city3: { value: "larvotto", label: "Larvotto" },
      city4: { value: "fontvieille", label: "Fontvieille" },
      city5: { value: "condamine", label: "Condamine" },
    },
  },
  {
    label: "Mongolia",
    value: "mongolia",
    cities: {
      city1: { value: "ulaanbaatar", label: "Ulaanbaatar" },
      city2: { value: "darkhan", label: "Darkhan" },
      city3: { value: "choibalsan", label: "Choibalsan" },
      city4: { value: "erenhot", label: "Erenhot" },
      city5: { value: "mandalgovi", label: "Mandalgovi" },
    },
  },
  {
    label: "Montenegro",
    value: "montenegro",
    cities: {
      city1: { value: "podgorica", label: "Podgorica" },
      city2: { value: "niksic", label: "Nikšić" },
      city3: { value: "herceg_novi", label: "Herceg Novi" },
      city4: { value: "pljevlja", label: "Pljevlja" },
      city5: { value: "bijelo_polje", label: "Bijelo Polje" },
    },
  },
  {
    label: "Morocco",
    value: "morocco",
    cities: {
      city1: { value: "casablanca", label: "Casablanca" },
      city2: { value: "rabat", label: "Rabat" },
      city3: { value: "fes", label: "Fes" },
      city4: { value: "marrakech", label: "Marrakech" },
      city5: { value: "tangier", label: "Tangier" },
    },
  },
  {
    label: "Mozambique",
    value: "mozambique",
    cities: {
      city1: { value: "maputo", label: "Maputo" },
      city2: { value: "matola", label: "Matola" },
      city3: { value: "beira", label: "Beira" },
      city4: { value: "nampula", label: "Nampula" },
      city5: { value: "chimoio", label: "Chimoio" },
    },
  },
  {
    label: "Myanmar",
    value: "myanmar",
    cities: {
      city1: { value: "naypyidaw", label: "Naypyidaw" },
      city2: { value: "yangon", label: "Yangon" },
      city3: { value: "mandalay", label: "Mandalay" },
      city4: { value: "mawlamyine", label: "Mawlamyine" },
      city5: { value: "bago", label: "Bago" },
    },
  },
  {
    label: "Namibia",
    value: "namibia",
    cities: {
      city1: { value: "windhoek", label: "Windhoek" },
      city2: { value: "swakopmund", label: "Swakopmund" },
      city3: { value: "walvis_bay", label: "Walvis Bay" },
      city4: { value: "oshakati", label: "Oshakati" },
      city5: { value: "rehoboth", label: "Rehoboth" },
    },
  },
  {
    label: "Nauru",
    value: "nauru",
    cities: {
      city1: { value: "yaren", label: "Yaren" },
      city2: { value: "buada", label: "Buada" },
      city3: { value: "anabar", label: "Anabar" },
      city4: { value: "meneng", label: "Meneng" },
      city5: { value: "eita", label: "Eita" },
    },
  },
  {
    label: "Nepal",
    value: "nepal",
    cities: {
      city1: { value: "kathmandu", label: "Kathmandu" },
      city2: { value: "pokhara", label: "Pokhara" },
      city3: { value: "lalitpur", label: "Lalitpur" },
      city4: { value: "bharatpur", label: "Bharatpur" },
      city5: { value: "biratnagar", label: "Biratnagar" },
    },
  },
  {
    label: "Netherlands",
    value: "netherlands",
    cities: {
      city1: { value: "amsterdam", label: "Amsterdam" },
      city2: { value: "rotterdam", label: "Rotterdam" },
      city3: { value: "the_hague", label: "The Hague" },
      city4: { value: "utrecht", label: "Utrecht" },
      city5: { value: "eindhoven", label: "Eindhoven" },
    },
  },
  {
    label: "New Zealand",
    value: "new_zealand",
    cities: {
      city1: { value: "auckland", label: "Auckland" },
      city2: { value: "wellington", label: "Wellington" },
      city3: { value: "christchurch", label: "Christchurch" },
      city4: { value: "hamilton", label: "Hamilton" },
      city5: { value: "napier", label: "Napier" },
    },
  },
  {
    label: "Nicaragua",
    value: "nicaragua",
    cities: {
      city1: { value: "managua", label: "Managua" },
      city2: { value: "leon", label: "León" },
      city3: { value: "masaya", label: "Masaya" },
      city4: { value: "matagalpa", label: "Matagalpa" },
      city5: { value: "chinandega", label: "Chinandega" },
    },
  },
  {
    label: "Niger",
    value: "niger",
    cities: {
      city1: { value: "niamey", label: "Niamey" },
      city2: { value: "zinder", label: "Zinder" },
      city3: { value: "maradi", label: "Maradi" },
      city4: { value: "agadez", label: "Agadez" },
      city5: { value: "tahoua", label: "Tahoua" },
    },
  },
  {
    label: "Nigeria",
    value: "nigeria",
    cities: {
      city1: { value: "lagos", label: "Lagos" },
      city2: { value: "kano", label: "Kano" },
      city3: { value: "abuja", label: "Abuja" },
      city4: { value: "ibadan", label: "Ibadan" },
      city5: { value: "port_harcourt", label: "Port Harcourt" },
    },
  },
  {
    label: "North Macedonia",
    value: "north_macedonia",
    cities: {
      city1: { value: "skopje", label: "Skopje" },
      city2: { value: "bitola", label: "Bitola" },
      city3: { value: "kumanovo", label: "Kumanovo" },
      city4: { value: "prilep", label: "Prilep" },
      city5: { value: "tetovo", label: "Tetovo" },
    },
  },
  {
    label: "Norway",
    value: "norway",
    cities: {
      city1: { value: "oslo", label: "Oslo" },
      city2: { value: "bergen", label: "Bergen" },
      city3: { value: "trondheim", label: "Trondheim" },
      city4: { value: "stavanger", label: "Stavanger" },
      city5: { value: "drammen", label: "Drammen" },
    },
  },
  {
    label: "Oman",
    value: "oman",
    cities: {
      city1: { value: "muscat", label: "Muscat" },
      city2: { value: "salalah", label: "Salalah" },
      city3: { value: "sohar", label: "Sohar" },
      city4: { value: "seeb", label: "Seeb" },
      city5: { value: "bawshar", label: "Bawshar" },
    },
  },
  {
    label: "Pakistan",
    value: "pakistan",
    cities: {
      city1: { value: "karachi", label: "Karachi" },
      city2: { value: "lahore", label: "Lahore" },
      city3: { value: "islamabad", label: "Islamabad" },
      city4: { value: "rawalpindi", label: "Rawalpindi" },
      city5: { value: "faisalabad", label: "Faisalabad" },
    },
  },
  {
    label: "Palau",
    value: "palau",
    cities: {
      city1: { value: "ngerulmud", label: "Ngerulmud" },
      city2: { value: "koror", label: "Koror" },
      city3: { value: "ngerkeai", label: "Ngerkeai" },
      city4: { value: "melekeok", label: "Melekeok" },
      city5: { value: "ngeard", label: "Ngeard" },
    },
  },
  {
    label: "Panama",
    value: "panama",
    cities: {
      city1: { value: "panama_city", label: "Panama City" },
      city2: { value: "san_miguelito", label: "San Miguelito" },
      city3: { value: "tocumen", label: "Tocumen" },
      city4: { value: "david", label: "David" },
      city5: { value: "las_cumbres", label: "Las Cumbres" },
    },
  },
  {
    label: "Papua New Guinea",
    value: "papua_new_guinea",
    cities: {
      city1: { value: "port_moresby", label: "Port Moresby" },
      city2: { value: "lae", label: "Lae" },
      city3: { value: "mount_hagen", label: "Mount Hagen" },
      city4: { value: "madang", label: "Madang" },
      city5: { value: "goroka", label: "Goroka" },
    },
  },
  {
    label: "Paraguay",
    value: "paraguay",
    cities: {
      city1: { value: "asuncion", label: "Asunción" },
      city2: { value: "ciudad_del_este", label: "Ciudad del Este" },
      city3: { value: "san_lorenzo", label: "San Lorenzo" },
      city4: { value: "luque", label: "Luque" },
      city5: { value: "capiata", label: "Capiatá" },
    },
  },
  {
    label: "Peru",
    value: "peru",
    cities: {
      city1: { value: "lima", label: "Lima" },
      city2: { value: "arequipa", label: "Arequipa" },
      city3: { value: "trujillo", label: "Trujillo" },
      city4: { value: "chiclayo", label: "Chiclayo" },
      city5: { value: "callao", label: "Callao" },
    },
  },
  {
    label: "Philippines",
    value: "philippines",
    cities: {
      city1: { value: "manila", label: "Manila" },
      city2: { value: "quezon_city", label: "Quezon City" },
      city3: { value: "caloocan", label: "Caloocan" },
      city4: { value: "davao_city", label: "Davao City" },
      city5: { value: "cavite_city", label: "Cavite City" },
    },
  },
  {
    label: "Poland",
    value: "poland",
    cities: {
      city1: { value: "warsaw", label: "Warsaw" },
      city2: { value: "krakow", label: "Kraków" },
      city3: { value: "lodz", label: "Łódź" },
      city4: { value: "wroclaw", label: "Wrocław" },
      city5: { value: "poznan", label: "Poznań" },
    },
  },
  {
    label: "Portugal",
    value: "portugal",
    cities: {
      city1: { value: "lisbon", label: "Lisbon" },
      city2: { value: "porto", label: "Porto" },
      city3: { value: "vila_nova_de_gaia", label: "Vila Nova de Gaia" },
      city4: { value: "amadora", label: "Amadora" },
      city5: { value: "braga", label: "Braga" },
    },
  },
  {
    label: "Qatar",
    value: "qatar",
    cities: {
      city1: { value: "doha", label: "Doha" },
      city2: { value: "al_wakrah", label: "Al Wakrah" },
      city3: { value: "al_rayyan", label: "Al Rayyan" },
      city4: { value: "umm_salal", label: "Umm Salal" },
      city5: { value: "al_khor", label: "Al Khor" },
    },
  },
  {
    label: "Romania",
    value: "romania",
    cities: {
      city1: { value: "bucharest", label: "Bucharest" },
      city2: { value: "cluj_napoca", label: "Cluj-Napoca" },
      city3: { value: "timisoara", label: "Timisoara" },
      city4: { value: "iasi", label: "Iasi" },
      city5: { value: "constanta", label: "Constanta" },
    },
  },
  {
    label: "Russia",
    value: "russia",
    cities: {
      city1: { value: "moscow", label: "Moscow" },
      city2: { value: "saint_petersburg", label: "Saint Petersburg" },
      city3: { value: "novosibirsk", label: "Novosibirsk" },
      city4: { value: "yekaterinburg", label: "Yekaterinburg" },
      city5: { value: "nizhny_novgorod", label: "Nizhny Novgorod" },
    },
  },
  {
    label: "Rwanda",
    value: "rwanda",
    cities: {
      city1: { value: "kigali", label: "Kigali" },
      city2: { value: "butare", label: "Butare" },
      city3: { value: "gitarama", label: "Gitarama" },
      city4: { value: "ruhengeri", label: "Ruhengeri" },
      city5: { value: "gisenyi", label: "Gisenyi" },
    },
  },
  {
    label: "Saint Kitts and Nevis",
    value: "saint_kitts_and_nevis",
    cities: {
      city1: { value: "basseterre", label: "Basseterre" },
      city2: { value: "charlestown", label: "Charlestown" },
      city3: { value: "sandy_point_town", label: "Sandy Point Town" },
      city4: { value: "fig_tree", label: "Fig Tree" },
      city5: { value: "cayon", label: "Cayon" },
    },
  },
  {
    label: "Saint Lucia",
    value: "saint_lucia",
    cities: {
      city1: { value: "castries", label: "Castries" },
      city2: { value: "gros_islet", label: "Gros Islet" },
      city3: { value: "vieux_fort", label: "Vieux Fort" },
      city4: { value: "micoud", label: "Micoud" },
      city5: { value: "deniere_riviere", label: "Deniere Riviere" },
    },
  },
  {
    label: "Saint Vincent and the Grenadines",
    value: "saint_vincent_and_the_grenadines",
    cities: {
      city1: { value: "kingstown", label: "Kingstown" },
      city2: { value: "ar_nouveau", label: "Ar Nouveau" },
      city3: { value: "biabou", label: "Biabou" },
      city4: { value: "barrouallie", label: "Barrouallie" },
      city5: { value: "chateaubelair", label: "Chateaubelair" },
    },
  },
  {
    label: "Samoa",
    value: "samoa",
    cities: {
      city1: { value: "apia", label: "Apia" },
      city2: { value: "vaitele", label: "Vaitele" },
      city3: { value: "faleula", label: "Faleula" },
      city4: { value: "siusega", label: "Si'usega" },
      city5: { value: "malie", label: "Malie" },
    },
  },
  {
    label: "San Marino",
    value: "san_marino",
    cities: {
      city1: { value: "san_marino", label: "San Marino" },
      city2: { value: "serravalle", label: "Serravalle" },
      city3: { value: "borgo_maggiore", label: "Borgo Maggiore" },
      city4: { value: "domagnano", label: "Domagnano" },
      city5: { value: "fiorentino", label: "Fiorentino" },
    },
  },
  {
    label: "Sao Tome and Principe",
    value: "sao_tome_and_principe",
    cities: {
      city1: { value: "sao_tome", label: "São Tomé" },
      city2: { value: "trindade", label: "Trindade" },
      city3: { value: "santana", label: "Santana" },
      city4: { value: "santo_amaro", label: "Santo Amaro" },
      city5: { value: "neves", label: "Neves" },
    },
  },
  {
    label: "Saudi Arabia",
    value: "saudi_arabia",
    cities: {
      city1: { value: "riyadh", label: "Riyadh" },
      city2: { value: "jeddah", label: "Jeddah" },
      city3: { value: "mecca", label: "Mecca" },
      city4: { value: "medina", label: "Medina" },
      city5: { value: "al_dammam", label: "Al-Dammam" },
    },
  },
  {
    label: "Senegal",
    value: "senegal",
    cities: {
      city1: { value: "dakar", label: "Dakar" },
      city2: { value: "grand_dakar", label: "Grand Dakar" },
      city3: { value: "thies", label: "Thies" },
      city4: { value: "saint_louis", label: "Saint-Louis" },
      city5: { value: "kaolack", label: "Kaolack" },
    },
  },
  {
    label: "Serbia",
    value: "serbia",
    cities: {
      city1: { value: "belgrade", label: "Belgrade" },
      city2: { value: "novi_sad", label: "Novi Sad" },
      city3: { value: "nis", label: "Niš" },
      city4: { value: "kragujevac", label: "Kragujevac" },
      city5: { value: "subotica", label: "Subotica" },
    },
  },
  {
    label: "Seychelles",
    value: "seychelles",
    cities: {
      city1: { value: "victoria", label: "Victoria" },
      city2: { value: "anse_royale", label: "Anse Royale" },
      city3: { value: "cascade", label: "Cascade" },
      city4: { value: "takamaka", label: "Takamaka" },
      city5: { value: "port_glaud", label: "Port Glaud" },
    },
  },
  {
    label: "Sierra Leone",
    value: "sierra_leone",
    cities: {
      city1: { value: "freetown", label: "Freetown" },
      city2: { value: "bo", label: "Bo" },
      city3: { value: "kenema", label: "Kenema" },
      city4: { value: "koidu", label: "Koidu" },
      city5: { value: "makeni", label: "Makeni" },
    },
  },
  {
    label: "Singapore",
    value: "singapore",
    cities: {
      city1: { value: "singapore", label: "Singapore" },
      city2: { value: "woodlands", label: "Woodlands" },
      city3: { value: "jurong_west", label: "Jurong West" },
      city4: { value: "tampines", label: "Tampines" },
      city5: { value: "sembawang", label: "Sembawang" },
    },
  },
  {
    label: "Slovakia",
    value: "slovakia",
    cities: {
      city1: { value: "bratislava", label: "Bratislava" },
      city2: { value: "kosice", label: "Košice" },
      city3: { value: "presov", label: "Prešov" },
      city4: { value: "nitra", label: "Nitra" },
      city5: { value: "zilina", label: "Žilina" },
    },
  },
  {
    label: "Slovenia",
    value: "slovenia",
    cities: {
      city1: { value: "ljubljana", label: "Ljubljana" },
      city2: { value: "maribor", label: "Maribor" },
      city3: { value: "celje", label: "Celje" },
      city4: { value: "kranj", label: "Kranj" },
      city5: { value: "velenje", label: "Velenje" },
    },
  },
  {
    label: "Solomon Islands",
    value: "solomon_islands",
    cities: {
      city1: { value: "honiara", label: "Honiara" },
      city2: { value: "guadalcanal", label: "Guadalcanal" },
      city3: { value: "auki", label: "Auki" },
      city4: { value: "gizo", label: "Gizo" },
      city5: { value: "buala", label: "Buala" },
    },
  },
  {
    label: "Somalia",
    value: "somalia",
    cities: {
      city1: { value: "mogadishu", label: "Mogadishu" },
      city2: { value: "hargeisa", label: "Hargeisa" },
      city3: { value: "berbera", label: "Berbera" },
      city4: { value: "kismayo", label: "Kismayo" },
      city5: { value: "marka", label: "Marka" },
    },
  },
  {
    label: "South Africa",
    value: "south_africa",
    cities: {
      city1: { value: "cape_town", label: "Cape Town" },
      city2: { value: "johannesburg", label: "Johannesburg" },
      city3: { value: "durban", label: "Durban" },
      city4: { value: "pretoria", label: "Pretoria" },
      city5: { value: "port_elizabeth", label: "Port Elizabeth" },
    },
  },
  {
    label: "South Korea",
    value: "south_korea",
    cities: {
      city1: { value: "seoul", label: "Seoul" },
      city2: { value: "busan", label: "Busan" },
      city3: { value: "incheon", label: "Incheon" },
      city4: { value: "daegu", label: "Daegu" },
      city5: { value: "daejeon", label: "Daejeon" },
    },
  },
  {
    label: "South Sudan",
    value: "south_sudan",
    cities: {
      city1: { value: "juba", label: "Juba" },
      city2: { value: "wau", label: "Wau" },
      city3: { value: "malakal", label: "Malakal" },
      city4: { value: "yambio", label: "Yambio" },
      city5: { value: "bor", label: "Bor" },
    },
  },
  {
    label: "Spain",
    value: "spain",
    cities: {
      city1: { value: "madrid", label: "Madrid" },
      city2: { value: "barcelona", label: "Barcelona" },
      city3: { value: "valencia", label: "Valencia" },
      city4: { value: "seville", label: "Seville" },
      city5: { value: "bilbao", label: "Bilbao" },
    },
  },
  {
    label: "Sri Lanka",
    value: "sri_lanka",
    cities: {
      city1: { value: "colombo", label: "Colombo" },
      city2: {
        value: "dehiwala_mount_lavinia",
        label: "Dehiwala-Mount Lavinia",
      },
      city3: { value: "moratuwa", label: "Moratuwa" },
      city4: { value: "negombo", label: "Negombo" },
      city5: { value: "kandy", label: "Kandy" },
    },
  },
  {
    label: "Sudan",
    value: "sudan",
    cities: {
      city1: { value: "khartoum", label: "Khartoum" },
      city2: { value: "oman", label: "Oman" },
      city3: { value: "nigeria", label: "Nigeria" },
      city4: { value: "niger", label: "Niger" },
      city5: { value: "nicaragua", label: "Nicaragua" },
    },
  },
  {
    label: "Suriname",
    value: "suriname",
    cities: {
      city1: { value: "paramaribo", label: "Paramaribo" },
      city2: { value: "lelydorp", label: "Lelydorp" },
      city3: { value: "brokopondo", label: "Brokopondo" },
      city4: { value: "nip", label: "Nieuw-Nickerie" },
      city5: { value: "moengo", label: "Moengo" },
    },
  },
  {
    label: "Swaziland",
    value: "swaziland",
    cities: {
      city1: { value: "mbabane", label: "Mbabane" },
      city2: { value: "manzini", label: "Manzini" },
      city3: { value: "lobamba", label: "Lobamba" },
      city4: { value: "siteki", label: "Siteki" },
      city5: { value: "big_bend", label: "Big Bend" },
    },
  },
  {
    label: "Sweden",
    value: "sweden",
    cities: {
      city1: { value: "stockholm", label: "Stockholm" },
      city2: { value: "gothenburg", label: "Gothenburg" },
      city3: { value: "malmo", label: "Malmö" },
      city4: { value: "uppsala", label: "Uppsala" },
      city5: { value: "västerås", label: "Västerås" },
    },
  },
  {
    label: "Switzerland",
    value: "switzerland",
    cities: {
      city1: { value: "zurich", label: "Zurich" },
      city2: { value: "geneva", label: "Geneva" },
      city3: { value: "basel", label: "Basel" },
      city4: { value: "bern", label: "Bern" },
      city5: { value: "lausanne", label: "Lausanne" },
    },
  },
  {
    label: "Syria",
    value: "syria",
    cities: {
      city1: { value: "damascus", label: "Damascus" },
      city2: { value: "aleppo", label: "Aleppo" },
      city3: { value: "homs", label: "Homs" },
      city4: { value: "hama", label: "Hama" },
      city5: { value: "latakia", label: "Latakia" },
    },
  },
  {
    label: "Taiwan",
    value: "taiwan",
    cities: {
      city1: { value: "taipei", label: "Taipei" },
      city2: { value: "kaohsiung", label: "Kaohsiung" },
      city3: { value: "taichung", label: "Taichung" },
      city4: { value: "tainan", label: "Tainan" },
      city5: { value: "banqiao", label: "Banqiao" },
    },
  },
  {
    label: "Tajikistan",
    value: "tajikistan",
    cities: {
      city1: { value: "dushanbe", label: "Dushanbe" },
      city2: { value: "khujand", label: "Khujand" },
      city3: { value: "kulyab", label: "Kulyab" },
      city4: { value: "qurghonteppa", label: "Qurghonteppa" },
      city5: { value: "kulob", label: "Kulob" },
    },
  },
  {
    label: "Tanzania",
    value: "tanzania",
    cities: {
      city1: { value: "dar_es_salaam", label: "Dar es Salaam" },
      city2: { value: "mwanza", label: "Mwanza" },
      city3: { value: "arusha", label: "Arusha" },
      city4: { value: "dodoma", label: "Dodoma" },
      city5: { value: "mbeya", label: "Mbeya" },
    },
  },
  {
    label: "Thailand",
    value: "thailand",
    cities: {
      city1: { value: "bangkok", label: "Bangkok" },
      city2: { value: "nonthaburi", label: "Nonthaburi" },
      city3: { value: "nakhon_ratchasima", label: "Nakhon Ratchasima" },
      city4: { value: "chiang_mai", label: "Chiang Mai" },
      city5: { value: "udon_thani", label: "Udon Thani" },
    },
  },
  {
    label: "Togo",
    value: "togo",
    cities: {
      city1: { value: "lome", label: "Lome" },
      city2: { value: "sokode", label: "Sokode" },
      city3: { value: "kara", label: "Kara" },
      city4: { value: "palime", label: "Palime" },
      city5: { value: "atakpame", label: "Atakpame" },
    },
  },
  {
    label: "Tonga",
    value: "tonga",
    cities: {
      city1: { value: "nuku_alofa", label: "Nuku'alofa" },
      city2: { value: "neiafu", label: "Neiafu" },
      city3: { value: "vaini", label: "Vaini" },
      city4: { value: "pangai", label: "Pangai" },
      city5: { value: "havelu", label: "Havelu" },
    },
  },
  {
    label: "Trinidad and Tobago",
    value: "trinidad_and_tobago",
    cities: {
      city1: { value: "port_of_spain", label: "Port of Spain" },
      city2: { value: "chaguanas", label: "Chaguanas" },
      city3: { value: "san_fernando", label: "San Fernando" },
      city4: { value: "arima", label: "Arima" },
      city5: { value: "point_fortin", label: "Point Fortin" },
    },
  },
  {
    label: "Tunisia",
    value: "tunisia",
    cities: {
      city1: { value: "tunis", label: "Tunis" },
      city2: { value: "sfax", label: "Sfax" },
      city3: { value: "sousse", label: "Sousse" },
      city4: { value: "kairouan", label: "Kairouan" },
      city5: { value: "bizerte", label: "Bizerte" },
    },
  },
  {
    label: "Turkey",
    value: "turkey",
    cities: {
      city1: { value: "istanbul", label: "Istanbul" },
      city2: { value: "ankara", label: "Ankara" },
      city3: { value: "izmir", label: "Izmir" },
      city4: { value: "bursa", label: "Bursa" },
      city5: { value: "adana", label: "Adana" },
    },
  },
  {
    label: "Turkmenistan",
    value: "turkmenistan",
    cities: {
      city1: { value: "ashgabat", label: "Ashgabat" },
      city2: { value: "turkmenabat", label: "Turkmenabat" },
      city3: { value: "dasoguz", label: "Dasoguz" },
      city4: { value: "mary", label: "Mary" },
      city5: { value: "balkanabat", label: "Balkanabat" },
    },
  },
  {
    label: "Tuvalu",
    value: "tuvalu",
    cities: {
      city1: { value: "funafuti", label: "Funafuti" },
      city2: { value: "alofau", label: "Alofau" },
      city3: { value: "vaiaku", label: "Vaiaku" },
      city4: { value: "lolua", label: "Lolua" },
      city5: { value: "faualu", label: "Faualu" },
    },
  },
  {
    label: "Uganda",
    value: "uganda",
    cities: {
      city1: { value: "kampala", label: "Kampala" },
      city2: { value: "gulu", label: "Gulu" },
      city3: { value: "lira", label: "Lira" },
      city4: { value: "mbarara", label: "Mbarara" },
      city5: { value: "jinja", label: "Jinja" },
    },
  },
  {
    label: "Ukraine",
    value: "ukraine",
    cities: {
      city1: { value: "kyiv", label: "Kyiv" },
      city2: { value: "kharkiv", label: "Kharkiv" },
      city3: { value: "odessa", label: "Odessa" },
      city4: { value: "dnipro", label: "Dnipro" },
      city5: { value: "lviv", label: "Lviv" },
    },
  },
  {
    label: "United Arab Emirates",
    value: "united_arab_emirates",
    cities: {
      city1: { value: "dubai", label: "Dubai" },
      city2: { value: "abu_dhabi", label: "Abu Dhabi" },
      city3: { value: "sharjah", label: "Sharjah" },
      city4: { value: "ajman", label: "Ajman" },
      city5: { value: "ras_al_khaimah", label: "Ras Al Khaimah" },
    },
  },
  {
    label: "United Kingdom",
    value: "united_kingdom",
    cities: {
      city1: { value: "london", label: "London" },
      city2: { value: "birmingham", label: "Birmingham" },
      city3: { value: "manchester", label: "Manchester" },
      city4: { value: "glasgow", label: "Glasgow" },
      city5: { value: "liverpool", label: "Liverpool" },
    },
  },
  {
    label: "United States",
    value: "united_states",
    cities: {
      city1: { value: "new_york_city", label: "New York City" },
      city2: { value: "los_angeles", label: "Los Angeles" },
      city3: { value: "chicago", label: "Chicago" },
      city4: { value: "houston", label: "Houston" },
      city5: { value: "miami", label: "Miami" },
      city6: { value: "washington_dc", label: "Washington D.C." },
      city7: { value: "atlanta", label: "Atlanta" },
      city8: { value: "san_francisco", label: "San Francisco" },
      city9: { value: "boston", label: "Boston" },
      city10: { value: "dallas", label: "Dallas" },
      city11: { value: "seattle", label: "Seattle" },
      city12: { value: "austin", label: "Austin" },
      city13: { value: "denver", label: "Denver" },
      city14: { value: "phoenix", label: "Phoenix" },
      city15: { value: "san_diego", label: "San Diego" },
      city16: { value: "orlando", label: "Orlando" },
      city17: { value: "philadelphia", label: "Philadelphia" },
      city18: { value: "las_vegas", label: "Las Vegas" },
      city19: { value: "detroit", label: "Detroit" },
      city20: { value: "minneapolis", label: "Minneapolis" },
      city21: { value: "tampa", label: "Tampa" },
      city22: { value: "phoenix", label: "Phoenix" },
      city23: { value: "baltimore", label: "Baltimore" },
      city24: { value: "portland", label: "Portland" },
      city25: { value: "san_antonio", label: "San Antonio" },
    },
  },
  {
    label: "Uruguay",
    value: "uruguay",
    cities: {
      city1: { value: "montevideo", label: "Montevideo" },
      city2: { value: "salto", label: "Salto" },
      city3: { value: "paysandu", label: "Paysandú" },
      city4: { value: "las_piedras", label: "Las Piedras" },
      city5: { value: "rivera", label: "Rivera" },
    },
  },
  {
    label: "Uzbekistan",
    value: "uzbekistan",
    cities: {
      city1: { value: "tashkent", label: "Tashkent" },
      city2: { value: "samarkand", label: "Samarkand" },
      city3: { value: "namangan", label: "Namangan" },
      city4: { value: "andijan", label: "Andijan" },
      city5: { value: "bukhara", label: "Bukhara" },
    },
  },
  {
    label: "Vanuatu",
    value: "vanuatu",
    cities: {
      city1: { value: "port_vila", label: "Port Vila" },
      city2: { value: "lakatoro", label: "Lakatoro" },
      city3: { value: "isangel", label: "Isangel" },
      city4: { value: "sola", label: "Sola" },
      city5: { value: "lenakel", label: "Lenakel" },
    },
  },
  {
    label: "Vatican City",
    value: "vatican_city",
    cities: {
      city1: { value: "vatican_city", label: "Vatican City" },
    },
  },
  {
    label: "Venezuela",
    value: "venezuela",
    cities: {
      city1: { value: "caracas", label: "Caracas" },
      city2: { value: "maracaibo", label: "Maracaibo" },
      city3: { value: "valencia", label: "Valencia" },
      city4: { value: "barquisimeto", label: "Barquisimeto" },
      city5: { value: "maracay", label: "Maracay" },
    },
  },
  {
    label: "Vietnam",
    value: "vietnam",
    cities: {
      city1: { value: "ho_chi_minh_city", label: "Ho Chi Minh City" },
      city2: { value: "hanoi", label: "Hanoi" },
      city3: { value: "da_nang", label: "Da Nang" },
      city4: { value: "hai_phong", label: "Hai Phong" },
      city5: { value: "can_tho", label: "Can Tho" },
    },
  },
  {
    label: "Yemen",
    value: "yemen",
    cities: {
      city1: { value: "sanaa", label: "Sanaa" },
      city2: { value: "taiz", label: "Taiz" },
      city3: { value: "aden", label: "Aden" },
      city4: { value: "al_hudaydah", label: "Al Hudaydah" },
      city5: { value: "ibb", label: "Ibb" },
    },
  },
  {
    label: "Zambia",
    value: "zambia",
    cities: {
      city1: { value: "lusaka", label: "Lusaka" },
      city2: { value: "ndola", label: "Ndola" },
      city3: { value: "kitwe", label: "Kitwe" },
      city4: { value: "kabwe", label: "Kabwe" },
      city5: { value: "chingola", label: "Chingola" },
    },
  },
  {
    label: "Zimbabwe",
    value: "zimbabwe",
    cities: {
      city1: { value: "harare", label: "Harare" },
      city2: { value: "bulawayo", label: "Bulawayo" },
      city3: { value: "chitungwiza", label: "Chitungwiza" },
      city4: { value: "mutare", label: "Mutare" },
      city5: { value: "gweru", label: "Gweru" },
    },
  },
];
