export const initialState = {
    personal: {
      firstName: "",
      lastName: "",
      gender: "",
      maritalStatus: "",
      occupation: "",
      phoneNumber: "",
      alternatePhoneNumber: "",
      country: "nigeria",
      state: "",
      zipCode: "",
      block: "",
      street: "",
      image: null,
    },
    estate: {
      name: "",
      email: "",
      phoneNumber: "",
      state: "",
      zipCode: "",
      block: "",
      street: "",
      country: "",
      type: "residential",
    },
    staff: {
      firstName: "",
      lastName: "",
      gender: "",
      maritalStatus: "",
      jobTitle: "",
      phoneNumber: "",
      alternatePhoneNumber: "",
      country: "",
      state: "",
      zipCode: "",
      block: "",
      street: "",
      image: null,
      email: "",
    },
    card: {
      cardHolderName: "",
      cardNumber: "",
      expirationDate: "",
      cvv: "",
    },
  }